export  const ACTION_TYPES= {
GET_EMPLOYEE:'GET_EMPLOYEE',
EDIT_EMPLOYEE:'EDIT_EMPLOYEE',
DELETE_EMPLOYEE:'DELETE_EMPLOYEE',
ADD_EMPLOYEE:'ADD_EMPLOYEE',
ADD_AVATAR:'ADD_AVATAR',
GET_AVATAR:'GET_AVATAR',
ADD_EMPLOYEE_IMAGE:'ADD_EMPLOYEE_IMAGE'
}

export const FETCH_PRODUCTS = "FETCH_PRODUCTS";
export const ADD_SELECT_PRODUCT="ADD_SELECT_PRODUCT";
export const REMOVE_SELECT_PRODUCT="REMOVE_SELECT_PRODUCT"
export const MAKE_PRIMARY_PRODUCT="MAKE_PRIMARY_PRODUCT"

